# basic options
title: AtsutoB's Blog
author: Data driven project management
email: atsutobriggs@gmail.com
description: >-
  Exploring data-driven approaches to project management in construction.
  Tutorials on APIs, business intelligence, text analytics, and practical
  solutions for construction project challenges.
twitter_username: atsutobriggs
github_username:  AtsutoB

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink structure
permalink: /:year/:month/:day/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md
